services:
  mysql:
    image: jsec/f1db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: f1
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
